/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primerainterfazjava;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier Martin Lorenzo <javiermartin.gara@gmail.com>
 */
public class PrimeraInterfazJava extends javax.swing.JFrame {

    /**
     * Creates new form PrimeraInterfazJava
     */
    public PrimeraInterfazJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaInformacion = new javax.swing.JTextArea();
        lblIntroducir = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        mnbMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuAbrir = new javax.swing.JMenuItem();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        txaInformacion.setEditable(false);
        txaInformacion.setColumns(20);
        txaInformacion.setLineWrap(true);
        txaInformacion.setRows(5);
        jScrollPane1.setViewportView(txaInformacion);

        lblIntroducir.setText("Introducir texto");

        btnEnviar.setText("Enviar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar(evt);
            }
        });

        mnuArchivo.setText("ARCHIVO");

        mnuAbrir.setText("Abrir");
        mnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivo(evt);
            }
        });
        mnuArchivo.add(mnuAbrir);

        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivo(evt);
            }
        });
        mnuArchivo.add(mnuGuardar);

        mnbMenu.add(mnuArchivo);

        mnuAyuda.setText("Ayuda");
        mnbMenu.add(mnuAyuda);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblIntroducir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntroducir)
                    .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar
        // Inserto el texto dentro del textArea
        txaInformacion.insert(txtTexto.getText() + "\n", txaInformacion.getText().length());
        // Limpio el textField
        txtTexto.setText("");
    }//GEN-LAST:event_enviar

    private void abrirArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivo
        // Abrir el gestor de archivos
        JFileChooser buscarArchivo = new JFileChooser();
        buscarArchivo.setFileSelectionMode((JFileChooser.FILES_AND_DIRECTORIES));
        int resultado = buscarArchivo.showOpenDialog(this);
        
        // Recoger el fichero seleccionado
        File archivo = buscarArchivo.getSelectedFile(); 
        
        try {
            // Al aceptar recoger el archivo
            if (resultado == JFileChooser.APPROVE_OPTION) {
                // Muestrar error si NO es válido
                if ((archivo == null) || (archivo.getName().equals(""))) {
                    JOptionPane.showMessageDialog(this, "Nombre de archivo inválido", "Nombre de archivo inválido", JOptionPane.ERROR_MESSAGE);
                }
                // Limpiar el textArea
                txaInformacion.setText("");
                
                // Agregar texto del archivo al textArea
                Scanner scn = new Scanner(archivo);
                while (scn.hasNext()) {
                    txaInformacion.insert(scn.nextLine() + "\n", txaInformacion.getText().length());
                }
                // Mostar en el título la dirección del archivo
                setTitle(archivo.getAbsolutePath());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PrimeraInterfazJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirArchivo

    private void guardarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivo
        // Abrir el gestor de archivos
        JFileChooser crearArchivo = new JFileChooser();
        crearArchivo.setDialogType(JFileChooser.SAVE_DIALOG);
        int resultado = crearArchivo.showSaveDialog(this);
        
        // Crear un nuevo archivo
        File archivo = crearArchivo.getSelectedFile();
                
        try {
            // Al aceptar se rellena y guarda el nuevo archivo
            if (resultado == JFileChooser.APPROVE_OPTION) {
                FileWriter fileWriter = new FileWriter(archivo.getAbsolutePath());
                BufferedWriter br = new BufferedWriter(fileWriter);
                br.write(txaInformacion.getText());
                br.close();
                
                // Mostar en el título la dirección del archivo
                setTitle(archivo.getAbsolutePath());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error con el Archivo", "Error con el Archivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarArchivo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterfazJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterfazJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterfazJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterfazJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraInterfazJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntroducir;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JTextArea txaInformacion;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
