/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor.view;

/**
 *
 * @author Javier Martin Lorenzo <javiermartin.gara@gmail.com>
 */
public class TraducirView extends javax.swing.JFrame {

    /**
     * Creates new form TraducirView
     */
    public TraducirView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmAniadir = new javax.swing.JFrame();
        pnlTraductor = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnTraducir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaIdiomaSecundario = new javax.swing.JTextArea();
        cmbIdiomaSecundario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaIdiomaPrincipal = new javax.swing.JTextArea();
        cmbIdiomaPrincipal = new javax.swing.JComboBox<>();
        pnlAniadir = new javax.swing.JPanel();
        btnSalirAniadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAniadir = new javax.swing.JButton();
        txtEspaniol = new javax.swing.JTextField();
        txtIngles = new javax.swing.JTextField();
        txtFrances = new javax.swing.JTextField();
        lblErrorAniadir = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnTraducir = new javax.swing.JMenu();
        jmnAniadir = new javax.swing.JMenu();

        javax.swing.GroupLayout frmAniadirLayout = new javax.swing.GroupLayout(frmAniadir.getContentPane());
        frmAniadir.getContentPane().setLayout(frmAniadirLayout);
        frmAniadirLayout.setHorizontalGroup(
            frmAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmAniadirLayout.setVerticalGroup(
            frmAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(15, 80, 180));
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Cerrar la aplicación");

        btnTraducir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTraducir.setForeground(new java.awt.Color(15, 80, 180));
        btnTraducir.setText("Traducir");
        btnTraducir.setToolTipText("Traducir de un idioma a otro");
        btnTraducir.setEnabled(false);

        txaIdiomaSecundario.setColumns(20);
        txaIdiomaSecundario.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        txaIdiomaSecundario.setRows(5);
        txaIdiomaSecundario.setToolTipText("Campo de texto del idioma secundario");
        jScrollPane2.setViewportView(txaIdiomaSecundario);

        cmbIdiomaSecundario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbIdiomaSecundario.setForeground(new java.awt.Color(15, 80, 180));
        cmbIdiomaSecundario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Castellano", "Inglés", "Francés" }));
        cmbIdiomaSecundario.setToolTipText("Seleccion del idioma secundario");

        txaIdiomaPrincipal.setColumns(20);
        txaIdiomaPrincipal.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        txaIdiomaPrincipal.setRows(5);
        txaIdiomaPrincipal.setToolTipText("Campo de texto del idioma principal");
        jScrollPane1.setViewportView(txaIdiomaPrincipal);

        cmbIdiomaPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbIdiomaPrincipal.setForeground(new java.awt.Color(15, 80, 180));
        cmbIdiomaPrincipal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Castellano", "Inglés", "Francés" }));
        cmbIdiomaPrincipal.setToolTipText("Selector del idioma principal");
        cmbIdiomaPrincipal.setFocusable(false);

        javax.swing.GroupLayout pnlTraductorLayout = new javax.swing.GroupLayout(pnlTraductor);
        pnlTraductor.setLayout(pnlTraductorLayout);
        pnlTraductorLayout.setHorizontalGroup(
            pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTraductorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlTraductorLayout.createSequentialGroup()
                            .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(cmbIdiomaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbIdiomaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlTraductorLayout.createSequentialGroup()
                            .addGap(344, 344, 344)
                            .addComponent(btnTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlTraductorLayout.setVerticalGroup(
            pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
            .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTraductorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbIdiomaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbIdiomaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(pnlTraductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTraducir)
                        .addComponent(btnSalir))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnSalirAniadir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalirAniadir.setForeground(new java.awt.Color(15, 80, 180));
        btnSalirAniadir.setText("Salir");
        btnSalirAniadir.setToolTipText("Cerrar la aplicación");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Introduce una nueva palabra al diccionario");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 80, 180));
        jLabel2.setText("Castellano");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 80, 180));
        jLabel3.setText("Inglés");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 80, 180));
        jLabel4.setText("Francés");

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(15, 80, 180));
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);

        btnAniadir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAniadir.setForeground(new java.awt.Color(15, 80, 180));
        btnAniadir.setText("Añadir");
        btnAniadir.setEnabled(false);

        txtEspaniol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtIngles.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtFrances.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblErrorAniadir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblErrorAniadir.setForeground(new java.awt.Color(187, 0, 0));

        javax.swing.GroupLayout pnlAniadirLayout = new javax.swing.GroupLayout(pnlAniadir);
        pnlAniadir.setLayout(pnlAniadirLayout);
        pnlAniadirLayout.setHorizontalGroup(
            pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAniadirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAniadirLayout.createSequentialGroup()
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlAniadirLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(66, 66, 66))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAniadirLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(119, 119, 119)))
                            .addGroup(pnlAniadirLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(97, 97, 97)))
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrances, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnSalirAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(pnlAniadirLayout.createSequentialGroup()
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlAniadirLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblErrorAniadir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAniadirLayout.setVerticalGroup(
            pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAniadirLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAniadirLayout.createSequentialGroup()
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtFrances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAniadirLayout.createSequentialGroup()
                        .addComponent(btnAniadir)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalirAniadir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblErrorAniadir)
                .addContainerGap())
        );

        jmnTraducir.setText("Traducir");
        jmnTraducir.setToolTipText("Vista del traductor");
        jmnTraducir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jmnTraducir);

        jmnAniadir.setText("Añadir");
        jmnAniadir.setToolTipText("Agregar una nueva palabra al diccionario");
        jmnAniadir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jmnAniadir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTraductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTraductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraducirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraducirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraducirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraducirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraducirView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAniadir;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSalirAniadir;
    public javax.swing.JButton btnTraducir;
    public javax.swing.JComboBox<String> cmbIdiomaPrincipal;
    public javax.swing.JComboBox<String> cmbIdiomaSecundario;
    public javax.swing.JFrame frmAniadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JMenu jmnAniadir;
    public javax.swing.JMenu jmnTraducir;
    public javax.swing.JLabel lblErrorAniadir;
    public javax.swing.JPanel pnlAniadir;
    public javax.swing.JPanel pnlTraductor;
    public javax.swing.JTextArea txaIdiomaPrincipal;
    public javax.swing.JTextArea txaIdiomaSecundario;
    public javax.swing.JTextField txtEspaniol;
    public javax.swing.JTextField txtFrances;
    public javax.swing.JTextField txtIngles;
    // End of variables declaration//GEN-END:variables
}
