/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiontareas.view;

/**
 *
 * @author Javier Martin Lorenzo <javiermartin.gara@gmail.com>
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddTareaModal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtActividad = new javax.swing.JTextField();
        txtAsignatura = new javax.swing.JTextField();
        spnDia = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dlgHistorial = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInfoTareasVencidas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        dlgUpdateTareaModal = new javax.swing.JDialog();
        spnDiaUpd = new javax.swing.JSpinner();
        btnEditar = new javax.swing.JButton();
        btnCancelarUpd = new javax.swing.JButton();
        cmbTareas = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ckbTerminar = new javax.swing.JCheckBox();
        lblActividadUpd = new javax.swing.JLabel();
        lblAsignaturaUpd = new javax.swing.JLabel();
        lblDiaUpd = new javax.swing.JLabel();
        txtActividadUpd = new javax.swing.JTextField();
        txtAsignaturaUpd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInforTareas = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 100, 200));
        jLabel1.setText("Agregar Tarea");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Actividad");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Asignatura");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Día");
        jLabel4.setToolTipText("");

        txtActividad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtActividad.setToolTipText("Nombre de la tarea");

        txtAsignatura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAsignatura.setToolTipText("Asignatura de la tarea");

        spnDia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        spnDia.setModel(new javax.swing.SpinnerDateModel());
        spnDia.setToolTipText("Dia de entrega de la tarea");

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Crear una nueva tarea");

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar la accion");

        javax.swing.GroupLayout dlgAddTareaModalLayout = new javax.swing.GroupLayout(dlgAddTareaModal.getContentPane());
        dlgAddTareaModal.getContentPane().setLayout(dlgAddTareaModalLayout);
        dlgAddTareaModalLayout.setHorizontalGroup(
            dlgAddTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddTareaModalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
            .addGroup(dlgAddTareaModalLayout.createSequentialGroup()
                .addGroup(dlgAddTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgAddTareaModalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dlgAddTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(dlgAddTareaModalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        dlgAddTareaModalLayout.setVerticalGroup(
            dlgAddTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddTareaModalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(dlgAddTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 300));

        txaInfoTareasVencidas.setEditable(false);
        txaInfoTareasVencidas.setColumns(20);
        txaInfoTareasVencidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txaInfoTareasVencidas.setLineWrap(true);
        txaInfoTareasVencidas.setRows(5);
        txaInfoTareasVencidas.setToolTipText("Lista de tareas vencidas");
        txaInfoTareasVencidas.setAutoscrolls(false);
        jScrollPane2.setViewportView(txaInfoTareasVencidas);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 100, 200));
        jLabel6.setText("Tareas vencidas");

        javax.swing.GroupLayout dlgHistorialLayout = new javax.swing.GroupLayout(dlgHistorial.getContentPane());
        dlgHistorial.getContentPane().setLayout(dlgHistorialLayout);
        dlgHistorialLayout.setHorizontalGroup(
            dlgHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgHistorialLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgHistorialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgHistorialLayout.setVerticalGroup(
            dlgHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgHistorialLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        spnDiaUpd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        spnDiaUpd.setModel(new javax.swing.SpinnerDateModel());
        spnDiaUpd.setToolTipText("Modificar dia de entrega de la tarea");
        spnDiaUpd.setEnabled(false);

        btnEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Modificación en la tarea");
        btnEditar.setEnabled(false);

        btnCancelarUpd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelarUpd.setText("Cancelar");
        btnCancelarUpd.setToolTipText("Cancelar la accion");

        cmbTareas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----" }));
        cmbTareas.setToolTipText("Selector de tarea para modificar/eliminar");

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar una tarea");
        btnEliminar.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 100, 200));
        jLabel7.setText("Editor Tareas");

        ckbTerminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ckbTerminar.setText("Terminar Tarea");
        ckbTerminar.setToolTipText("Dar por terminada una tarea");
        ckbTerminar.setEnabled(false);

        lblActividadUpd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblActividadUpd.setText("Actividad");
        lblActividadUpd.setToolTipText("");
        lblActividadUpd.setEnabled(false);

        lblAsignaturaUpd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAsignaturaUpd.setText("Asignatura");
        lblAsignaturaUpd.setToolTipText("");
        lblAsignaturaUpd.setEnabled(false);

        lblDiaUpd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDiaUpd.setText("Día");
        lblDiaUpd.setToolTipText("");
        lblDiaUpd.setEnabled(false);

        txtActividadUpd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtActividadUpd.setToolTipText("Nombre de la tarea");
        txtActividadUpd.setEnabled(false);

        txtAsignaturaUpd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAsignaturaUpd.setToolTipText("Asignatura de la tarea");
        txtAsignaturaUpd.setEnabled(false);

        javax.swing.GroupLayout dlgUpdateTareaModalLayout = new javax.swing.GroupLayout(dlgUpdateTareaModal.getContentPane());
        dlgUpdateTareaModal.getContentPane().setLayout(dlgUpdateTareaModalLayout);
        dlgUpdateTareaModalLayout.setHorizontalGroup(
            dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarUpd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addComponent(txtActividadUpd)
                        .addGap(14, 14, 14))
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addComponent(cmbTareas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addComponent(lblDiaUpd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addComponent(txtAsignaturaUpd)
                        .addGap(14, 14, 14))
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addComponent(spnDiaUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(ckbTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                        .addGroup(dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActividadUpd)
                            .addComponent(lblAsignaturaUpd))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgUpdateTareaModalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgUpdateTareaModalLayout.setVerticalGroup(
            dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgUpdateTareaModalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cmbTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActividadUpd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActividadUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAsignaturaUpd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsignaturaUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDiaUpd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnDiaUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTerminar))
                .addGap(27, 27, 27)
                .addGroup(dlgUpdateTareaModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelarUpd))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        txaInforTareas.setEditable(false);
        txaInforTareas.setColumns(20);
        txaInforTareas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txaInforTareas.setLineWrap(true);
        txaInforTareas.setRows(5);
        txaInforTareas.setToolTipText("Lista de tareas pendientes");
        txaInforTareas.setAutoscrolls(false);
        jScrollPane1.setViewportView(txaInforTareas);

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Agregar una nueva tarea");

        btnHistorial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.setToolTipText("Mostrar el historial de tareas");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 100, 200));
        jLabel5.setText("Tareas pendientes de realizar");

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Editar o eliminar una tarea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnModificar)
                    .addComponent(btnHistorial)
                    .addComponent(btnAgregar))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAgregar)
                        .addGap(30, 30, 30)
                        .addComponent(btnHistorial)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCancelarUpd;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnHistorial;
    public javax.swing.JButton btnModificar;
    public javax.swing.JCheckBox ckbTerminar;
    public javax.swing.JComboBox<String> cmbTareas;
    public javax.swing.JDialog dlgAddTareaModal;
    public javax.swing.JDialog dlgHistorial;
    public javax.swing.JDialog dlgUpdateTareaModal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblActividadUpd;
    public javax.swing.JLabel lblAsignaturaUpd;
    public javax.swing.JLabel lblDiaUpd;
    public javax.swing.JSpinner spnDia;
    public javax.swing.JSpinner spnDiaUpd;
    public javax.swing.JTextArea txaInfoTareasVencidas;
    public javax.swing.JTextArea txaInforTareas;
    public javax.swing.JTextField txtActividad;
    public javax.swing.JTextField txtActividadUpd;
    public javax.swing.JTextField txtAsignatura;
    public javax.swing.JTextField txtAsignaturaUpd;
    // End of variables declaration//GEN-END:variables
}
